### ISSUE TITLE
Resolve these UI changes

### ISSUE THREAD

**Issue by saankalpaa** [smrkarkii/portfolio#15]
- Make sure the download cv text doesn't disappear on hover.
- make sure the UI is consistent. Currently, the first section is intro is white then about me is blue then my projects is white but skills is not blue. So, here if you make the background of skills blue then it would look good.
- Also the titles are not of the same font size and font weight.
- I can see that you have put skills like a card but every other section is not like that so make sure you maintain consistency here too.
- Make sure the font color of the input field is a bit dark.

<img width="449" alt="image" src="https://user-images.githubusercontent.com/61270616/183278498-95c4a5c0-7f90-4e14-a125-c9a689249c3d.png">

**Comment by smrkarkii** [comment]
please have a loot at t.
