### ISSUE TITLE
after submitting form link back to portfolio is wrong

### ISSUE THREAD

**Issue by saankalpaa** [smrkarkii/portfolio#16]
After you submit the form the redirection back to the portfolio is wrong. Make sure you resolve this issue.
<img width="1440" alt="Screen Shot 2022-08-07 at 12 23 22" src="https://user-images.githubusercontent.com/61270616/183278612-8b3e7412-f46c-47f4-bfaf-97549c1299fb.png">

**Comment by saankalpaa** [comment]
I think you forgot to add /portfolio in hyperlink.

**Comment by smrkarkii** [comment]
done
