### ISSUE TITLE
Minor UI changes

### ISSUE THREAD

**Issue by Anurodhyadav** [smrkarkii/portfolio#18]
1) Please add scroll-behaviour as smooth on the links in the navbar
2) I think adding some sort of minor animation when user hover on to my-projects section would be better
  a) You can have color change on hover
  b) Or else you can make it popup slightly with the help of scale on hover
  c) The input boxes in **Get in touch** sections does not matches with the width of my-project sections in the mobile view.
  d) Add a link to projects when user clicks on your projects in the my project sections.
3) Make sure user is sent to new tab when he/she clicks on social media account logos.
4) when i clicked on instagram logo, it did not took me to your account page.

**Comment by smrkarkii** [comment]
please have a look at changes.

**Comment by Anurodhyadav** [comment]
Looks good @smrkarkii . Very good job with the changes
